version: 2.1
jobs:
  test:
    docker:
      - image: cicleci/node:10.17
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run testremote
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - test
